# Generated by Django 5.1.4 on 2025-01-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='detail',
            new_name='article',
        ),
    ]
